-- Generated by nwg-displays on 2026-10-05 at 11:39:59. Do not edit manually.

hl.workspace_rule({
    workspace = "6",
    monitor = "DP-1",
    default = true
})
hl.workspace_rule({
    workspace = "7",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1"
})
