# run code --list-extensions to get the list of extensions and update this file

code --install-extension adpyke.vscode-sql-formatter
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension bierner.lit-html
code --install-extension bierner.markdown-mermaid
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-highlight
code --install-extension foam.foam-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension graphql.vscode-graphql-syntax
code --install-extension hashicorp.terraform
code --install-extension kortina.vscode-markdown-notes
code --install-extension kukushi.pasteurl
code --install-extension lanza.lldb-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension mushan.vscode-paste-image
code --install-extension pomdtr.excalidraw-editor
code --install-extension prisma.prisma
code --install-extension rust-lang.rust-analyzer
code --install-extension saoudrizwan.claude-dev # cline
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tamasfe.even-better-toml
code --install-extension tomoki1207.pdf
code --install-extension twxs.cmake
code --install-extension vadimcn.vscode-lldb
code --install-extension vue.volar
code --install-extension yangtangwu.html-to-markdown
code --install-extension yzhang.markdown-all-in-one