#!/bin/bash
# Backup script: syncs $HOME dir with Backblaze

echo "-----> Running backup script on $(date +"%Y-%m-%d-%H:%M:%S")"

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FILTER_FILE="$SCRIPT_DIR/backup_directories.txt"

# other options for running it manually: --dry-run --progress
rclone copy --copy-links --transfers 8 --max-buffer-memory 1G --filter-from="$FILTER_FILE" $HOME backblaze:poposbkp

echo "-----> Backup finished on $(date +"%Y-%m-%d-%H:%M:%S")"
if command -v notify-send &> /dev/null
then
    notify-send "Backup finished" "$(date +"%Y-%m-%d-%H:%M:%S")"
fi


# Command to Check backup size
# du -ch -d 3 \
#   "$HOME/code" "$HOME/Documents" "$HOME/Pictures" "$HOME/Videos" "$HOME/Music" \
#   --exclude='.*/**' --exclude='tmp/**' --exclude='sandbox/**' --exclude='go/**' --exclude='apps/**' \
#   --exclude='node_modules/**' --exclude='__pycache__/**' --exclude='miniconda3/**' \
#   --exclude='VirtualBoxVMs/**' --exclude='Downloads/**' --exclude='canvas-lms/**' \
#   ~/ | sort -rh | head -20
