#!/bin/bash
# Restore $HOME from the Backblaze backup.

set -Eeuo pipefail

DESTINATION="${1:-$HOME}"
shift || true

echo "-----> Restoring backblaze:poposbkp to $DESTINATION"
rclone copy --fast-list --update --progress "$@" backblaze:poposbkp "$DESTINATION"
